### ISSUE TITLE
Incompatible with ES 2.3

### ISSUE THREAD

**Issue by LRancez** [jurgc11/es-change-feed-plugin#1]
Hi there,
Thanks for sharing this cool plugin.
But it seems that is not compatible with the version 2.3 of ES.

```
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [es-changes-feed-plugin] is incompatible with Elasticsearch [2.3.1]. Was designed for version [2.2.0]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

Can you update the plugin?
Thanks!!!

**Comment by jurgc11** [comment]
Hi Lucas,

Sorry for the very late reply, for some reason I didn't receive a notification from GitHub. 

Since I intend to skip directly to ES 5 when it's released I probably won't be building a 2.3 version of the plugin. Having said that, if you feel like doing it, i'm happy to make you a collaborator.

Thanks,
Chris

**Comment by LRancez** [comment]
Hi @jurgc11, thanks for the response.

Be aware that the ES 5 is not even in beta state yet and that there is no roadmap or timeline publicly available for when 5 is expected to be production ready.

On the other hand, sadly I don't currently have an available time to code this project.
If anyone else is up for it, please contact @jurgc11 
Best,

**Comment by jurgc11** [comment]
I've just released a new build of the plugin which supports v2.3.5, so i'll close the issue.
